name: Update README cards

on:
  schedule:
    - cron: "0 3 * * *" 
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate stats card
        # Sửa lại từ anuraghazra thành readme-tools
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true&count_private=true&title_color=ffd1dc&text_color=ffd1dc&icon_color=ffd1dc&ring_color=89b4fa&bg_color=45,0d1117,1a1a2e&border_color=ffd1dc&locale=en
          path: profile-summary/stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate top langs card
        # Sửa lại từ anuraghazra thành readme-tools
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&layout=compact&langs_count=5&hide=HTML,CSS,Jupyter%20Notebook&title_color=ffd1dc&text_color=ffd1dc&bg_color=45,0d1117,1a1a2e&border_color=ffd1dc&locale=en
          path: profile-summary/langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          mkdir -p profile-summary
          git add profile-summary/*.svg
          git commit -m "Update README cards" || exit 0
          git push
